### PR TITLE
small code duplication

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
I noticed this small code duplication. Why is code duplication set so high?

https://github.com/vanheeringen-lab/ANANSE/blob/refactor/.codeclimate.yml#L4

### CODE REVIEW

**Review by siebrenf — APPROVED** [review]
we could up the threshold to 4, but it did help you find this ugly duplication ;)

**Comment by Maarten-vd-Sande** [comment]
The other way around @siebrenf, I wanted to reduce it to 1. It did not help me find it, I found i _by accident_. However there is this piece of code it says its a duplication but it isnt

**Comment by siebrenf** [comment]
ah, my bad (need more coffee!) 
These numbers came from genomepy, so they may not apply here! Feel free to experiment. I think CC will show any new issues that pop up in a PR with new settings, so you can do so here, or in a new PR.

**Comment by simonvh** [comment]
Closing this PR, as `ananse/binding/py` will be deleted with the `peakpredictor` merge, and `ananse/influence.py` is already adapted by @Maarten-vd-Sande in another PR.

**Pull request closed without merging**
