### PR TITLE
Action from fork

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
This is a test :D

### CODE REVIEW

**Comment by siebrenf** [comment]
I had to manually merge develop back into this branch for some reason :/ 
not sure why it's showing changes already present in develop now, but the tests should work again!

**Comment by Maarten-vd-Sande** [comment]
Why did you change it that it doesn't run on other branches?

**Comment by siebrenf** [comment]
To prevent double workflow executions on branches with PRs (save our precious monthly minutes).

**Comment by Maarten-vd-Sande** [comment]
I don't really see a point since we never had issues with that on github but sure

**Pull request merged**
