### PR TITLE
QoL for binding

### PR DESCRIPTION
**Pull request by siebrenf**
* binding -r can use s2s count table directly
* better docs

### CODE REVIEW

**Comment by simonvh** [comment]
@siebrenf is the idea that you can also use the counts from the table then directly? That would be a nice addition :)

**Review by simonvh — COMMENTED** [review]
This uses the regions from the s2s table right, not the quantification (i.e. read counts)?

**Comment by siebrenf** [comment]
correct. 

executive summary for s2s count tables:
```
# load the whole file as a tsv full of strings, if there is a header, pretend its a row
df = pd.read_table(infile, header=None, sep="\t", comment="#", dtype=str)

# take the first column
regions = df.iloc[:, 0].tolist()

# if row 1 is a header, remove it.
header = str(regions[0])
if not bool(re.match(r"^.*:\d+-\d+$", header)):
    regions = regions[1:]
```

**Review by simonvh — APPROVED** [review]

**Comment by simonvh** [comment]
> correct.

I think this is already a great addition. However, we could also use the counts in the table, which means the quantification from the BAMs is not necessary. Anyway, that can be another improvement later down the line.

**Comment by siebrenf** [comment]
agreed on both accounts :)

**Pull request merged**
